"""Continuation IX — Final Digital Release Lock (pre-EVT OS lock).

PHYSICAL_EXECUTION_FREEZE remains active. No purchase/merge claims.
RECREATION_READY ≠ REPRODUCIBLE_READY. Adopter readiness does not require open hardware.
"""
from __future__ import annotations

CLAIM_BOUNDARY = (
    "Continuation IX digital release lock only. "
    "No physical EVT/DVT/PVT, no production HSM keys, no MS Office fidelity claims, "
    "no carrier certification, no store submission. "
    "RECREATION_DIGITAL_READY ≠ REPRODUCIBILITY_DIGITAL_READY."
)

# Cont IX readiness tokens (earned only when clean-env / built proofs pass)
TOKEN_PRODUCTIVITY_INSTALL = "GUNNCHOS_PRODUCTIVITY_REAL_INSTALL_DIGITAL_PASS"
TOKEN_BROWSER = "GUNNCHOS_BROWSER_DIGITAL_PASS"
TOKEN_OFFICE_FILES = "GUNNCHOS_OFFICE_FILES_E2E_DIGITAL_PASS"
TOKEN_PDF = "GUNNCHOS_PDF_DIGITAL_PASS"
TOKEN_EMAIL_CAL = "GUNNCHOS_EMAIL_CALENDAR_DIGITAL_PASS"
TOKEN_VIDEO = "GUNNCHOS_VIDEO_MEETING_DIGITAL_PASS"
TOKEN_CUPS = "GUNNCHOS_CUPS_VIRTUAL_DIGITAL_PASS"
TOKEN_VPN = "GUNNCHOS_VPN_ENTERPRISE_DIGITAL_PASS"
TOKEN_STUDENT_READY = "GUNNCHOS_STUDENT_DIGITAL_READY"
TOKEN_OFFICE_READY = "GUNNCHOS_OFFICE_WORK_DIGITAL_READY"
TOKEN_RECREATION_READY = "GUNNCHOS_RECREATION_DIGITAL_READY"
TOKEN_RING_APP = "GUNNCHOS_RING_APP_E2E_DIGITAL_PASS"
TOKEN_ADOPTER_READY = "GUNNCHOS_ADOPTER_DIGITAL_READY"
TOKEN_API_COMPAT = "GUNNCHOS_API_COMPAT_DIGITAL_PASS"
TOKEN_REPRO_READY = "GUNNCHOS_REPRODUCIBILITY_DIGITAL_READY"
TOKEN_FACTORY = "GUNNCHOS_FACTORY_LINE_DIGITAL_PASS"
TOKEN_SECURITY = "GUNNCHOS_SECURITY_HARDENING_DIGITAL_PASS"
TOKEN_A11Y = "GUNNCHOS_A11Y_HARDENING_DIGITAL_PASS"
TOKEN_STORAGE_PERF = "GUNNCHOS_STORAGE_PERF_MODELS_DIGITAL_PASS"
TOKEN_BATTERY_THERMAL = "GUNNCHOS_BATTERY_THERMAL_HANDOFF_DIGITAL_PASS"
TOKEN_SUPPORT = "GUNNCHOS_SUPPORT_SELF_SERVICE_DIGITAL_PASS"
TOKEN_DOCS = "GUNNCHOS_ADOPTER_USER_DOCS_DIGITAL_PASS"
TOKEN_DIGITAL_LOCK = "GUNNCHOS_DIGITAL_RELEASE_LOCK_PASS"
