"""WP-013 CLI handlers wired into `gunnchctl` (see
`gunnchos_device_os/device_lab/cli.py`): `os-image`, `sdk`, `package`,
`install`, and the SDK-package branch of `run`.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def default_install_root(repo_root: Path) -> Path:
    return repo_root / "os_build" / "sdk_runtime" / "installed"


# ----------------------------------------------------------------------
# os-image
# ----------------------------------------------------------------------
def cmd_os_image(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    from gunnchos_device_os.release_engineering.os_image_builder import RealmImageBuilder

    builder = RealmImageBuilder(repo_root)
    if ns.os_image_cmd == "build":
        return builder.build(ns.realm, unsigned=bool(ns.unsigned))
    if ns.os_image_cmd == "inspect":
        return builder.inspect(ns.realm)
    if ns.os_image_cmd == "verify":
        return builder.verify(ns.realm)
    return {"ok": False, "error": f"unknown_os_image_cmd:{ns.os_image_cmd}"}


# ----------------------------------------------------------------------
# sdk init|build|test
# ----------------------------------------------------------------------
def cmd_sdk(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    if ns.sdk_cmd == "init":
        return _sdk_init(ns, repo_root)
    if ns.sdk_cmd == "build":
        return _sdk_build(ns, repo_root)
    if ns.sdk_cmd == "test":
        return _sdk_test(ns, repo_root)
    return {"ok": False, "error": f"unknown_sdk_cmd:{ns.sdk_cmd}"}


def _sdk_init(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    from gunnchos_device_os.release_engineering.sdk.manifest import new_manifest

    app_dir = Path(ns.path)
    if app_dir.exists() and any(app_dir.iterdir()):
        return {"ok": False, "error": "target_dir_not_empty", "path": str(app_dir)}
    app_dir.mkdir(parents=True, exist_ok=True)
    manifest = new_manifest(app_id=ns.app_id, name=ns.name or ns.app_id)
    (app_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    (app_dir / "main.py").write_text(
        "#!/usr/bin/env python3\n"
        '"""gunnchSDK app generated by `gunnchctl sdk init`."""\n'
        "import json, os\n\n\n"
        "def main() -> int:\n"
        "    print(json.dumps({\"ok\": True, \"app_id\": os.environ.get(\"GUNNCHOS_APP_ID\")}))\n"
        "    return 0\n\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())\n",
        encoding="utf-8",
    )
    return {"ok": True, "app_dir": str(app_dir), "app_id": ns.app_id, "manifest": manifest}


def _sdk_build(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    from gunnchos_device_os.release_engineering.sdk.packager import PackageBuilder

    builder = PackageBuilder(repo_root)
    out_dir = Path(ns.out) if ns.out else repo_root / "os_build" / "sdk_runtime" / "packages"
    result = builder.build(Path(ns.path), out_dir, sign=not ns.unsigned)
    return result


def _sdk_test(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    import tempfile

    from gunnchos_device_os.release_engineering.sdk.installer import PackageInstaller
    from gunnchos_device_os.release_engineering.sdk.manifest import validate_manifest
    from gunnchos_device_os.release_engineering.sdk.packager import PackageBuilder
    from gunnchos_device_os.release_engineering.sdk.runner import PackageRunner

    app_dir = Path(ns.path)
    manifest_path = app_dir / "manifest.json"
    if not manifest_path.exists():
        return {"ok": False, "error": "manifest_missing", "path": str(manifest_path)}
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest_failures = validate_manifest(manifest)

    with tempfile.TemporaryDirectory(prefix="gunnchsdk_test_") as tmp:
        tmp_path = Path(tmp)
        builder = PackageBuilder(repo_root)
        try:
            build_result = builder.build(app_dir, tmp_path / "pkgs")
        except Exception as exc:
            return {"ok": False, "error": "build_failed", "detail": str(exc), "manifest_failures": manifest_failures}

        installer = PackageInstaller(repo_root, tmp_path / "install")
        install_result = installer.install(Path(build_result["package_path"]))
        if not install_result.get("ok"):
            return {"ok": False, "error": "install_failed", "install_result": install_result}

        runner = PackageRunner(tmp_path / "install")
        run_result = runner.run(install_result["app_id"])

        return {
            "ok": bool(run_result.get("ok")) and not manifest_failures,
            "manifest_failures": manifest_failures,
            "build": {"ok": build_result["ok"], "signed": build_result["signed"]},
            "install": {"ok": install_result["ok"], "gate_warnings": install_result.get("gate_warnings", [])},
            "run": {"ok": run_result.get("ok"), "exit_code": run_result.get("exit_code")},
            "SDK_PACKAGE_INSTALL_RUN_PASS": bool(run_result.get("ok")) and not manifest_failures,
        }


# ----------------------------------------------------------------------
# package | install | run(sdk-branch)
# ----------------------------------------------------------------------
def cmd_package(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    from gunnchos_device_os.release_engineering.sdk.packager import PackageBuilder

    out_dir = Path(ns.out) if ns.out else repo_root / "os_build" / "sdk_runtime" / "packages"
    return PackageBuilder(repo_root).build(Path(ns.app_dir), out_dir, sign=not ns.unsigned)


def cmd_install(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    from gunnchos_device_os.release_engineering.sdk.installer import PackageInstaller

    install_root = Path(ns.install_root) if ns.install_root else default_install_root(repo_root)
    installer = PackageInstaller(repo_root, install_root)
    if getattr(ns, "update", False):
        return installer.update(Path(ns.package))
    return installer.install(Path(ns.package), force=bool(ns.force))


def cmd_uninstall(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    from gunnchos_device_os.release_engineering.sdk.installer import PackageInstaller

    install_root = Path(ns.install_root) if ns.install_root else default_install_root(repo_root)
    return PackageInstaller(repo_root, install_root).uninstall(ns.app_id, keep_logs=bool(ns.keep_logs))


def cmd_run_sdk_package(ns: argparse.Namespace, repo_root: Path) -> dict[str, Any]:
    from gunnchos_device_os.release_engineering.sdk.runner import PackageRunner

    install_root = Path(getattr(ns, "install_root", None) or default_install_root(repo_root))
    return PackageRunner(install_root).run(ns.app, args=getattr(ns, "app_args", None) or None)
