[core]
idle-time=0
require-input=false

[shell]
panel-position=top
locking=false
animation=zoom
startup-animation=fade
# gunnchOS branding overlays provided by launcher package

[launcher]
icon=/usr/share/weston/icon_terminal.png
path=/usr/bin/weston-terminal

[output]
name=headless
mode=1280x800
