/** Shared shell surface IDs — keep navigation meaning stable across form factors. */
export type Cx2Surface =
  | 'home'
  | 'vault'
  | 'app_center'
  | 'connect'
  | 'assist'
  | 'care'
  | 'wallet'
  | 'portfolio'
  | 'career'
  | 'verifier'
  | 'settings'
  | 'search'
  | 'waike'
  | 'gunnchai'
  | 'games'
  | 'creation'
  | 'leisure'
