requirements:
  School:
    keyboard: true
  Developer:
    keyboard: true
  Workshop:
    keyboard: true
  Laboratory:
    keyboard: true
  Play:
    controller: optional
  Arcade:
    controller: recommended
  Media:
    touch: true
