"""Continuation VIII — release readiness (Lanes F, G, I).

Digital-only execution. PHYSICAL_EXECUTION_FREEZE remains active.
No purchase, no merge claims, no physical measurement claims.
"""
from __future__ import annotations

TOKEN_PRODUCTIVITY_STACK_PASS = "GUNNCHOS_PRODUCTIVITY_STACK_DIGITAL_PASS"
TOKEN_STUDENT_E2E_PASS = "GUNNCHOS_STUDENT_E2E_DIGITAL_PASS"
TOKEN_OFFICE_E2E_PASS = "GUNNCHOS_OFFICE_E2E_DIGITAL_PASS"
TOKEN_OFFICE_FILE_COMPAT_PASS = "GUNNCHOS_OFFICE_FILE_COMPAT_DIGITAL_PASS"
TOKEN_ADOPTER_SDK_PASS = "GUNNCHOS_ADOPTER_SDK_DIGITAL_PASS"
TOKEN_API_ABI_PASS = "GUNNCHOS_API_ABI_POLICY_DIGITAL_PASS"
TOKEN_REPRO_PASS = "GUNNCHOS_REPRODUCIBILITY_DIGITAL_PASS"
TOKEN_FACTORY_PASS = "GUNNCHOS_FACTORY_STATION_DIGITAL_PASS"
TOKEN_DEVICE_MGMT_PASS = "GUNNCHOS_DEVICE_MGMT_DIGITAL_PASS"
TOKEN_BASELINES_PASS = "GUNNCHOS_SEC_A11Y_OFFLINE_NET_DIGITAL_PASS"
TOKEN_MEDIA_PASS = "GUNNCHOS_MEDIA_BASELINE_DIGITAL_PASS"
TOKEN_DOCK_DAILY_PASS = "GUNNCHOS_DOCK_DAILY_WORKFLOW_DIGITAL_PASS"
TOKEN_PERF_MODELS_PASS = "GUNNCHOS_PERF_MODELS_DIGITAL_PASS"
TOKEN_AUDIENCE_DOCS_PASS = "GUNNCHOS_AUDIENCE_DOCS_DIGITAL_PASS"
TOKEN_RELEASE_SCORECARD_PASS = "GUNNCHOS_RELEASE_SCORECARD_DIGITAL_PASS"
TOKEN_RECREATION_REPROVE_PASS = "GUNNCHOS_RECREATION_REPROVE_DIGITAL_PASS"

CLAIM_BOUNDARY = (
    "Continuation VIII digital release-readiness only. "
    "No physical EVT/DVT/PVT, no production HSM keys, no MS Office fidelity claims, "
    "no carrier certification, no store submission."
)
