"""Phase XV — final digital closure for residual OS frontier gates.

PHYSICAL_EXECUTION_FREEZE=ACTIVE. Does NOT claim GUNNCHOS_FRONTIER_OS_PARITY.
auto_merge_request remains null; DRAFT PRs only.
"""
from __future__ import annotations

PHASE_XV_VERSION = "0.1.0-phase-xv"
PHYSICAL_EXECUTION_FREEZE = True
FRONTIER_OS_PARITY_CLAIMED = False
GUNNCHOS_FRONTIER_OS_PARITY = False

DIGITALLY_VALIDATED = "DIGITALLY_VALIDATED"
INCOMPLETE_DIGITAL = "INCOMPLETE_DIGITAL"
PHYSICAL_PENDING = "PHYSICAL_PENDING"
EXTERNAL_PENDING = "EXTERNAL_PENDING"

__all__ = [
    "PHASE_XV_VERSION",
    "PHYSICAL_EXECUTION_FREEZE",
    "FRONTIER_OS_PARITY_CLAIMED",
    "GUNNCHOS_FRONTIER_OS_PARITY",
    "DIGITALLY_VALIDATED",
    "INCOMPLETE_DIGITAL",
    "PHYSICAL_PENDING",
    "EXTERNAL_PENDING",
]
